name: portfolio
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  font_awesome_flutter: ^9.2.0
  avatar_glow: ^2.0.2
  shimmer: ^2.0.0
  badges: ^2.0.2
  flutter_swiper: ^1.1.6
  animated_text_kit: ^4.2.1
  flutter_slider_drawer: ^2.1.1
  url_launcher: ^6.0.20
  scrollable_positioned_list: ^0.2.3
  dotted_border: ^1.0.7
  animated_background: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: Sequel 100 Black
      fonts:
        - asset: assets/fonts/Sequel100Black-45.ttf
          weight: 300
    - family: Sequel 100 Black
      fonts:
        - asset: assets/fonts/Sequel100Black-65.ttf
          weight: 400
    - family: Sequel 100 Black 95
      fonts:
        - asset: assets/fonts/Sequel100Black-95.ttf
          weight: 500
    - family: Sequel 100 Black 105
      fonts:
        - asset: assets/fonts/Sequel100Black-105.ttf
          weight: 600
    - family: Century Gothic
      fonts:
        - asset: assets/fonts/centuryGothic.ttf
